Repository e2e-win/e2e-win-prow-deployment, pull requests merged in 2018-07, with the labels that each got.

#19 [images] Changed the way go is installed
  images/acs_engine_prow_test/Dockerfile
Labels: approved, lgtm

#21 Remove locations
  images/acs_engine_prow_test/build.sh
Labels: approved, size/S

#20 [images] Added new image to build the acs_engine_prow_test one
  images/acs_engine_prow_build/Dockerfile
  images/acs_engine_prow_build/Makefile
  images/acs_engine_prow_build/build_acs_e2e.sh
Labels: approved, lgtm, size/L

#12 [image-build] Added PR merge
  images/kubekins_build/Dockerfile
  images/kubekins_build/Makefile
  images/kubekins_build/build_kubekins_e2e.sh
Labels: approved, lgtm

#22 Add artifacts dir for kubetest dump
  images/acs_engine_prow_test/build.sh
Labels: size/XS

#23 Fix typo in build.sh
  images/acs_engine_prow_test/build.sh
Labels: size/XS

#24 Temp revert to kubernetes 1.10 for testing
  images/acs_engine_prow_test/build.sh
Labels: size/XS

#25 Revert "Temp revert to kubernetes 1.10 for testing"
  images/acs_engine_prow_test/build.sh
Labels: size/XS

#26 Schrodingers glide.
  images/acs_engine_prow_test/build.sh
Labels: size/XS

#31 Added KUBECTL_PATH env var
  images/kubetest_build/build_kubetest.sh
Labels: size/XS

#32 Added file with skipped conformance tests
  exclude_conformance_test.txt
Labels: approved, lgtm, needs-ok-to-test, size/M

#33 [custom-scripts] add script for taking logs from windows slaves
  custom-scripts/master.sh
Labels: approved, lgtm, size/M

#37 Settle on exclusion list for tests.
  images/acs_engine_prow_test/build.sh
Labels: size/XS

#38 [images-kubetest] made a wrapper for az to censor vars
  images/kubetest_build/build_kubetest.sh
Labels: approved, lgtm, size/XS

#39 Revert "[images-kubetest] made a wrapper for az to censor vars"
  images/kubetest_build/build_kubetest.sh
Labels: size/XS

#40 [images-kubetest] made a wrapper for az to censor vars
  images/kubetest_build/build_kubetest.sh
Labels: approved, lgtm, size/S
